{{- if .Values.migration.weblate.customResourcesPath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrationservice-resource-{{ .Release.Name }}-configmap
data:
  {{- $path := printf "%s/*.json" "customization/migrationservice-resources" }}
    {{- (.Files.Glob $path).AsConfig | nindent 2 }}
{{- end }}
