{{- if .Values.global.translationManagementSystemEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
  namespace: weblate-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: saas
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.2.1
    helm.sh/chart: redis-18.1.1
type: Opaque
data:
  redis-password: {{ .Values.redisPassword | b64enc | quote }}
{{- end }}
