{{- if .Values.global.translationManagementSystemEnabled }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "weblate.serviceAccountName" . }}
  namespace: weblate-{{ .Release.Namespace }}
  labels:
{{ include "weblate.labels" . | indent 4 }}
{{- end -}}
{{- end }}
