keycloakImageName: "ghcr.io/onlineberatung/onlineberatung-keycloak-otp/onlineberatung-keycloak-otp"
keycloakVersion: "develop_20221121_165617"

dbVendor: "MARIADB"
dbDatabase: "keycloak"

# Logging
# Supported log levels are ALL, DEBUG, ERROR, FATAL, INFO, OFF, TRACE and WARN.
keycloakLogLevel: "WARN"
rootLogLevel: "WARN"

keycloakDbUser: "keycloak"
keycloakDbPassword: "keycloak"